# -*- coding: utf-8 -*-
"""Classifier.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RjKd606q-Ceri0YeuEW15z5zoy7GvT0f
"""

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC
from sklearn.metrics import accuracy_score

# Read data from files
def read_file(filename):
    f = open(filename, "r", encoding="utf-8")
    lines = f.readlines()
    f.close()
    return [line.strip() for line in lines]

sport_texts = read_file("sports.txt")
politics_texts = read_file("politics.txt")

texts = sport_texts + politics_texts
labels = ["sport"] * len(sport_texts) + ["politics"] * len(politics_texts)

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    texts, labels, test_size=0.2, random_state=42
)

# Feature extraction (TF-IDF)
vectorizer = TfidfVectorizer(ngram_range=(1,2))
X_train_vec = vectorizer.fit_transform(X_train)
X_test_vec = vectorizer.transform(X_test)

# Models
nb_model = MultinomialNB()
lr_model = LogisticRegression(max_iter=1000)
svm_model = LinearSVC()

models = {
    "Naive Bayes": nb_model,
    "Logistic Regression": lr_model,
    "SVM": svm_model
}

# Train and evaluate
print("Training models...\n")

for name, model in models.items():
    model.fit(X_train_vec, y_train)
    predictions = model.predict(X_test_vec)
    acc = accuracy_score(y_test, predictions)
    print(name, "Accuracy:", round(acc * 100, 2), "%")

# Choose best model (SVM)
best_model = svm_model
best_model.fit(X_train_vec, y_train)

# Interactive prediction
print("\nEnter a sentence to classify (type 'exit' to quit):")

while True:
    user_input = input("You: ")

    if user_input.lower() == "exit":
        print("Bye!")
        break

    user_vec = vectorizer.transform([user_input])
    prediction = best_model.predict(user_vec)

    print("Prediction:", prediction[0])